export const LANGS = [
    { label: 'Arabic', value: 'ar' },
    { label: 'Bosnian', value: 'bs' },
    { label: 'Catalan', value: 'ca' },
    { label: 'Czech', value: 'cs' },
    { label: 'Danish', value: 'da' },
    { label: 'German', value: 'de' },
    { label: 'English', value: 'en' },
    { label: 'Spanish', value: 'es' },
    { label: 'Finnish', value: 'fi' },
    { label: 'French', value: 'fr' },
    { label: 'Croatian', value: 'hr' },
    { label: 'Indonesian', value: 'id' },
    { label: 'Korean', value: 'ko' },
    { label: 'Malay', value: 'ms' },
    { label: 'Norwegian (Bokmål)', value: 'nb' },
    { label: 'Dutch', value: 'nl' },
    { label: 'Norwegian (Nynorsk)', value: 'nn' },
    { label: 'Russian', value: 'ru' },
    { label: 'Polish', value: 'pl' },
    { label: 'Portuguese', value: 'pt' },
    { label: 'Swedish', value: 'sv' },
    { label: 'Tagalog', value: 'tl' },
    { label: 'Vietnamese', value: 'vi' },
    { label: 'Chinese', value: 'zh' },
];      