# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  #push:
  #  branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
        working-directory: ./vue-website
      - name: Build
        run: yarn run build
        working-directory: ./vue-website
      - name: Additional Deployment Step
        run: yarn run deploy
        working-directory: ./vue-website
      - name: Setup Pages
        uses: actions/configure-pages@v3
        working-directory: ./vue-website
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        working-directory: ./vue-website
        with:
          # Upload vite build output
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        working-directory: ./vue-website
        uses: actions/deploy-pages@v2
